
GET http://localhost:5197/main/assets
Cookie: AuthToken=asd
###
GET http://localhost:5197/main/assets/top_products/11
    

###
POST http://localhost:5197/
Content-Type: application/json

{
    "Username": "test",
    "Password": "123" 
}

###
POST http://localhost:5197/register
Content-Type: application/json

{
    "Username": "ahmet",
    "Password": "sifre12345" 
}

###
POST http://localhost:5197/main/assets
Content-Type: application/json
Cookie: AuthToken=asd

{
  "assetType": "Bağ",
  "provinceName": "Ankara",
  "districtName": "Gölbaşı",
  "neighborhoodName": "Seğmenler",
  "blockNumber": "000",
  "parcelNumber": "000",
  "plantedProduct": ""
}


###
POST http://localhost:5048/editAssets
Content-Type: application/json
Cookie: AuthToken=Sk8blM1OdDL2JVbY8wCJ2hqCcfu4gd9yXqA5HUWYQ+8=

{
  "assetType": "Bağ",
  "provinceName": "Ankara",
  "districtName": "Gölbaşı",
  "neighborhoodName": "Seğmenler",
  "blockNumber": "000",
  "parcelNumber": "000",
  "plantedProduct": ""
}

###
POST https://places.googleapis.com/v1/places:searchText 
Content-Type: application/json
X-Goog-Api-Key: AIzaSyApekf_lfBpdxJsc_k3yBQDlvgc3_Jw9Ws
X-Goog-FieldMask: places.displayName,places.formattedAddress
languageCode: tr

{
  "textQuery" : "ankara yemek"
}

###
GET https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=52.52&daily=rain_sum&past_days=3

###39.9334° N, 32.8597° E
GET https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&daily=rain_sum&past_days=2

###
GET https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=AIzaSyApekf_lfBpdxJsc_k3yBQDlvgc3_Jw9Ws

###
GET https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&daily=temperature_2m_max,temperature_2m_min&timezone=auto&past_days=3
